### ISSUE TITLE
roslaunch报错:ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex ERROR in osqp_setup: KKT matrix factorization. The problem seems to be non-convex. [OsqpEigen::Solver::initSolver] Unable to setup the workspace. [OsqpEigen::Solver::solveProblem] The solve has not been initialized yet. Please call initSolver() method. [OsqpEigen::Solver::solve] Unable to solve the problem.

### ISSUE THREAD

**Issue by P1terQ** [ShuoYangRobotics/A1-QP-MPC-Controller#18]
硕哥你好，我是在自己环境下编译你的文件的，没有error．但是在roslaunch unitree_gazebo，rosrun unitree_controller unitree_servo后roslaunch a1_cpp a1_ctrl.launch就会立刻报错，信息如下：
ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.
[OsqpEigen::Solver::initSolver] Unable to setup the workspace.
[OsqpEigen::Solver::solveProblem] The solve has not been initialized yet. Please call initSolver() method.
[OsqpEigen::Solver::solve] Unable to solve the problem.

请问硕哥这是为什么

**Comment by binfengxueqian** [comment]
您好，请问您这个问题最后是怎么解决的呢？

**Comment by binfengxueqian** [comment]
@P1terQ 
您好！请问您最后是怎么解决的这个问题呢？

**Comment by mitsui29** [comment]
你好，想问一下哈，这个问题是咋解决的阿？我也是单独运行没问题，但是一开但是在roslaunch unitree_gazebo，rosrun unitree_controller unitree_servo后roslaunch a1_cpp a1_ctrl.launch就会立刻报错：                                                                    ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.
[OsqpEigen::Solver::initSolver] Unable to setup the workspace.
[OsqpEigen::Solver::solveProblem] The solve has not been initialized yet. Please call initSolver() method.
[OsqpEigen::Solver::solve] Unable to solve the problem.
[gazebo_a1_ctrl-1] process has died [pid 247, exit code -11, cmd /root/A1_ctrl_ws/devel/lib/a1_cpp/gazebo_a1_ctrl __name:=gazebo_a1_ctrl __log:=/root/.ros/log/6ac58746-756a-11ee-a909-0cdd24a8d027/gazebo_a1_ctrl-1.log].
log file: /root/.ros/log/6ac58746-756a-11ee-a909-0cdd24a8d027/gazebo_a1_ctrl-1*.log
兄弟有什么建议吗？
