### ISSUE TITLE
Will this pkg be used in Go1 directly?

### ISSUE THREAD

**Issue by crankler** [ShuoYangRobotics/A1-QP-MPC-Controller#5]
Hi, will this pkg can be used in Unitree Go1  robot now?
and I'm not sure the contact detection can be change (I also found a pkg from Aaron lab: https://github.com/robomechanics/quad-sdk,
and I notice you also mentioned contact point in your newly pkg "legged-kinematics-calibration")

**Comment by ShuoYangRobotics** [comment]
Yes it can work for Go1 directly but some parameters should be changed slightly. create a new yaml for Go1 here
https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/tree/main/src/a1_cpp/config

Also our docker is build using old unitree_sdk version. To support Go1 you need to change sdk version 
(https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/blob/main/docker/Dockerfile#L141) Change this branch to a version that support Go1.

Contact detection does not need to be changed because A1 and Go1 use the same unitree SDK to read contact sensor data.

**Comment by crankler** [comment]
Yes, I'll try these day and thank your for your help!
